### ISSUE TITLE
GUI to dynamically change PWM.

### ISSUE THREAD

**Issue by ksakash** [AUV-IITK/Hyperion-Software#14]
It is very annoying to do thruster testing by writing each and every command on the terminal to test it. We can do it easily by dynamic reconfiguration.

**Comment by Suryansh470** [comment]
the GUI has already been developed ...call saini ..... !!!!! also you can use the rqt monitor to change the values on topics....

**Comment by Suryansh470** [comment]
For rqt monitor use rqt_publisher ...... all topics will appear one by one and u can change the values being published by just one click !!

**Comment by ksakash** [comment]
But that is in the development stage, we don't know how stable that is and creating a gui using dynamic reconfigure is very easy. We will also not require any other dependency, plus it is. For using rqt, we will need to install Qt.

**Comment by Mayankm96** [comment]
I am confused what exactly is wanted from the thruster testing GUI? By testing, you mean just to put PWM and see if the thruster works or not? In that case @pkhrag had made a GUI for this. It is available [here](https://github.com/AUV-IITK/Varun-Software/tree/master/debug_layer/remote_control).

Dynamic reconfiguration can be done but again it is used for parameters to your node instead of data to which your node subscribes to. Now, PWM would be topic messages while PID parameters are best suited for dynamic reconfiguration. So using dynamic reconfiguration is not suitable if you just want to pass PWM values. to node.

**Comment by Mayankm96** [comment]
What would be better to have a joystick controller for our vehicle through which we can give motion commands like (surge/sway/heave/roll/pitch/yaw) instead of each thruster individual PWM. 

Also for checking if the thruster is connected or not, we can use the status pins in motor drivers to check whether everything is fine at hardware level or not. While this was missing in `Varun`, I believe Nilay and Saksham are doing that in the new actuation board for the vehicle.

**Comment by ksakash** [comment]
I think GUI which @pkhrag has made is a keyboard controller, as I can infer from [here](https://github.com/AUV-IITK/Varun-Software/blob/master/debug_layer/remote_control/Controls.txt), to control the motion. So, it doesn't control individual thrusters. We need to dynamically set the `PWM` sent to thrusters too, for our testing purposes which we are unware of. The issue topic is misleading, sorry for that. Changing it right know.

**Comment by ksakash** [comment]
As pointed out by @Suryansh470 there is already a `ros` package `rqt_reconfigure` can be used for dynamically publishing values on a topic. So, closing this issue.

**Comment by Suryansh470** [comment]
there is another ```ros``` package of ```rqt``` to monitor that ..... just see that
